BigBazarMVCProject/Controllers/CategoryController.cs
using BigBazarMVCProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BigBazarMVCProject.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IManagerModel _managerModel;

        public CategoryController(IManagerModel managerModel)
        {
            _managerModel = managerModel;
        }
        // GET: CategoryController
        public async Task <IActionResult> GetCategories()
        {
            List<CategoryModel> categorys = await _managerModel.GetCategories();
            return View(categorys);
        }

       

        // GET: CategoryController/Create
        public ActionResult CreateCategory()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
      
        public async Task<IActionResult> CreateCategory(CategoryModel categoryModel)
        {
            if (await _managerModel.AddCategory(categoryModel))
            {
                return View();
            }

            return View();
        }


        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCategory( CategoryModel categoryModel)
        {
            bool result = await _managerModel.EditCategory(categoryModel);
            return View();

        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id , CategoryModel categoryModel)
        {
            if (await _managerModel.DeleteCategory(id))
            {
                return View();
            }
            return View();
        }
    }
}

BigBazarMVCProject/Controllers/CustomerController.cs
using BigBazarMVCProject.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BigBazarMVCProject.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IManagerModel _managerModel;
        public CustomerController(IManagerModel managerModel)
        {
            _managerModel = managerModel;
        }
        public ActionResult CreateCustomer()
        {
            return View();
        }

       
        [HttpPost]

        public async Task<IActionResult> CreateCustomer(CustomerModel customerModel)
        {
            if (await _managerModel.AddCustomer(customerModel))
            {
                return View();
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetCustomer()
        {
            List<CustomerModel> customers = await _managerModel.GetCustomerDetails();
            return View(customers);
        }
    }
}

BigBazarMVCProject/Controllers/ProductController.cs
using BigBazarMVCProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BigBazarMVCProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly IManagerModel _managerModel;
        public ProductController(IManagerModel managerModel)
        {
            _managerModel = managerModel;
        }
        // GET: ProductController
        public async Task <IActionResult> GetProducts()
        {
            List<ProductModel> products = await _managerModel.GetProducts();
            return View(products);
        }

        // GET: ProductController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductController/Create
        public ActionResult CreateProduct()
        {
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> CreateProduct(ProductModel productModel)
        {
            if (await _managerModel.AddProducts(productModel))
            {
                return View();
            }

            return View();
        }

        
     

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BigBazarMVCProject/Controllers/PurchaseController.cs
using BigBazarMVCProject.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BigBazarMVCProject.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly IManagerModel _managerModel;
        public PurchaseController(IManagerModel managerModel)
        {
            _managerModel = managerModel;
        }
        [HttpGet]
        public async Task<IActionResult> GetPurchaseListItems()
        {
            List<PurchaseModel> purchaseModels = await _managerModel.GetPurchaseList();
            return View(purchaseModels);
        }


        public ActionResult PurchaseItems()
        {
            return View();
        }

        
        [HttpPost]

        public async Task<IActionResult> PurchaseItems(PurchaseModel purchaseModel)
        {
            if (await _managerModel.AddItems(purchaseModel))
            {
                return View();
            }

            return View();
        }

        //public async Task<IActionResult> CalculateQuantity(int productId , int quantity)
        //{
        //    if(await _managerModel.CalculateQuantity(productId , quantity))
        //    {
        //        return View();
        //    }
        //    return View();
        //}
        [HttpGet]
        public ActionResult GetPurchaseById()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> GetPurchaseById(int id)
        {
            PurchaseModel purchaseModels = await _managerModel.GetPurchaseById(id);
            return View(purchaseModels);
            
        }

        [HttpGet]

        public async Task<IActionResult> GetReciept(int id)
        {
            PurchaseModel purchaseModel = await _managerModel.GetPurchaseById(id);
            RecieptModel recieptModel = new RecieptModel();
            recieptModel.Date = purchaseModel.DateOfPurchase;
            recieptModel.NoOfItems = purchaseModel.PurchaseQuantity;
            recieptModel.TotalBill = (purchaseModel.PurchasePrice) * (purchaseModel.PurchaseQuantity);
            return View(recieptModel);
        }
    }
}

BigBazarMVCProject/Controllers/UserController.cs
using BigBazar.Services;
using BigBazarMVCProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BigBazarMVCProject.Controllers
{
    public class UserController : Controller
    {
        

        private readonly IManagerModel _managerModel;
        public UserController(IManagerModel managerModel)
        {
            _managerModel = managerModel;
        }

        // GET: UserController
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserModel userModel)
        {
            
             
            if (await _managerModel.UserExist(userModel))
            {
                if (userModel.UserRole1.Equals("Admin"))
                {
                    return RedirectToAction("LoginAsAdmin");
                }
                else if (userModel.UserRole1.Equals("User"))
                {
                    return RedirectToAction("LoginAsUser");
                }
            }
            else
            {
                return RedirectToAction("CreateUserOrBackToLogin");
            }
            return View();
        }

        public ActionResult LoginAsAdmin()
        {
            return View();
        }

        public ActionResult LoginAsUser()
        {
            return View();
        }

     

        // GET: UserController1/Create
        public ActionResult CreateUser()
        {
            return View();
        }

        // POST: UserController1/Create
        [HttpPost]
       
        public async Task<IActionResult> CreateUser(UserModel userModel)
        {
            if(await _managerModel.AddUser(userModel))
                {
                    return View();
                }
            
            return View();
        }

      

       

    }
}

BigBazarMVCProject/Views/User/CreateUser.cshtml
@model BigBazarMVCProject.Models.UserModel

@{
    ViewData["Title"] = "CreateUser";
}

<h1>CreateUser</h1>


<hr />
<div class="row">
    <div class="col-md-4"  id="form">
        <form id="form" >
        @*<form asp-action="CreateUser">*@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserRole1" class="control-label"></label>
                <input asp-for="UserRole1" class="form-control" />
                <span asp-validation-for="UserRole1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" id="btnClick" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Login">Back to Login Page</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

  <script>
      $(document).ready(function () {
          $('#btnClick').click(function () {
              var data = $('#form').serialize();

              $.ajax({
                  type: 'POST',
                  url: '/User/CreateUser',
                  data: data,
                  success: function (data) {
                      alert("Congratulations! Account created successfully")
                  },
                  error: function (err) {
                      alert("Sorry! Account creation failed! Try again")
                  }
              })
          })
      })
  </script>
}

BigBazarMVCProject/Views/User/Login.cshtml
@model BigBazarMVCProject.Models.UserModel

@{
    ViewData["Title"] = "Login";
}

<h2><marquee direction="right">Welcomt to Big Bazar Login Page</marquee></h2>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .parallax {
          
            /* Set a specific height */
            min-height: 150px;
            /* Create the parallax scrolling effect */
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
</head>
<body>

   
<div class="parallax"></div>
<centre>


    <hr />
    @*<div style="background-image: url(D:\BigBazar1.jpeg)">*@

    <div class="row" style="background-color: darksalmon">
        <div class="col-md-4" id="form">
            <form id="form" action="/User/Login" method="post">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserRole1" class="control-label"></label>
                    <input asp-for="UserRole1" class="form-control" />
                    <span asp-validation-for="UserRole1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" id="btnClick" value="Login" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>


    <br />
    <br />
    <div style="background-color:aqua">
        <h4> @Html.ActionLink("Create User Account", "CreateUser")</h4>
    </div>
</centre>
    </body>
</html>

@section Scripts {



    <script>
        $(document).ready(function () {
            $('#btnClick').click(function () {
                var role = $('#UserRole1').val();
                if (role == "Admin") {
                    return true;
                }
                else if (role == "User") {
                    return true;
                }
                else

                    alert("Role must be either User or Admin");
                return false;

            })
        })
    </script>
}

BigBazarMVCProject/Views/User/LoginAsAdmin.cshtml
@{
    ViewData["Title"] = "LoginAsAdmin";
}

<h3><b style="color:brown"><marquee direction="right"> ADMIN OPERATIONS</marquee></b></h3>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        .mynav_navbar {
            overflow: hidden;
            background-color: #333;
            font-family: Arial;
        }

            /* Links inside the navbar */
            .mynav_navbar a {
                float: left;
                font-size: 16px;
                color: black;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

        /* The dropdown container */
        .mynav_dropdown {
            float: left;
            overflow: hidden;
        }

            /* Dropdown button */
            .mynav_dropdown .mynav_dropbtn {
                font-size: 16px;
                border: none;
                outline: none;
                color: white;
                padding: 14px 16px;
                background-color: inherit;
                font: inherit; /* Important for vertical align on mobile phones */
                margin: 0; /* Important for vertical align on mobile phones */
            }

            /* Add a red background color to navbar links on hover */
            .mynav_navbar a:hover, .mynav_dropdown:hover .mynav_dropbtn {
                background-color: darkviolet;
            }

        /* Dropdown content (hidden by default) */
        .mynav_dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            width: 100%;
            left: 0;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            /* Mega Menu header, if needed */
            .mynav_dropdown-content .mynav_header {
                background: red;
                padding: 16px;
                color: white;
            }

        /* Show the dropdown menu on hover */
        .mynav_dropdown:hover .mynav_dropdown-content {
            display: block;
        }

        /* Create three equal columns that floats next to each other */
        .mynav_column {
            float: left;
            width: 33.33%;
            padding: 10px;
            background-color: orangered;
        }

            /* Style links inside the columns */
            .mynav_column a {
                float: none;
                color: black;
                padding: 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                /* Add a background color on hover */
                .mynav_column a:hover {
                    background-color: darkviolet;
                }

        /* Clear floats after the columns */
        .mynav_row:after {
            content: "";
            display: table;
            clear: both;
        }
    </style>
</head>
<body>
    <div class="mynav_navbar">


        <div class="mynav_dropdown">
            <button class="mynav_dropbtn">
                Category
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="mynav_dropdown-content">

                <div class="row">
                    <div class="column">

                        @Html.ActionLink("Add Category", "CreateCategory", "Category")
                    </div>

                    <div class="column">
                        @Html.ActionLink("Get list of category", "GetCategories", "Category")
                    </div>
                </div>
            </div>
        </div>
        <div class="mynav_dropdown">
            <button class="mynav_dropbtn">
                Product
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="mynav_dropdown-content">

                <div class="row">
                    <div class="column">

                        @Html.ActionLink("Add Products", "CreateProduct", "Product")
                    </div>
                    <div class="column">
                        @Html.ActionLink("Get Products", "GetProducts", "Product")
                    </div>

                </div>
            </div>
        </div>
      
    </div>
</body>
</html>





   

BigBazarMVCProject/Views/User/LoginAsUser.cshtml
@{
    ViewData["Title"] = "LoginAsUser";
}

<h3><b style="color:brown"><marquee direction="right"> USER OPERATIONS</marquee></b></h3>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        .mynav_navbar {
            overflow: hidden;
            background-color: #333;
            font-family: Arial;
        }

            /* Links inside the navbar */
            .mynav_navbar a {
                float: left;
                font-size: 16px;
                color: black;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

        /* The dropdown container */
        .mynav_dropdown {
            float: left;
            overflow: hidden;
        }

            /* Dropdown button */
            .mynav_dropdown .mynav_dropbtn {
                font-size: 16px;
                border: none;
                outline: none;
                color: white;
                padding: 14px 16px;
                background-color: inherit;
                font: inherit; /* Important for vertical align on mobile phones */
                margin: 0; /* Important for vertical align on mobile phones */
            }

            /* Add a red background color to navbar links on hover */
            .mynav_navbar a:hover, .mynav_dropdown:hover .mynav_dropbtn {
                background-color: darkviolet;
            }

        /* Dropdown content (hidden by default) */
        .mynav_dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            width: 100%;
            left: 0;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            /* Mega Menu header, if needed */
            .mynav_dropdown-content .mynav_header {
                background: red;
                padding: 16px;
                color: white;
            }

        /* Show the dropdown menu on hover */
        .mynav_dropdown:hover .mynav_dropdown-content {
            display: block;
        }

        /* Create three equal columns that floats next to each other */
        .mynav_column {
            float: left;
            width: 33.33%;
            padding: 10px;
            background-color: orangered;
        }

            /* Style links inside the columns */
            .mynav_column a {
                float: none;
                color: black;
                padding: 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                /* Add a background color on hover */
                .mynav_column a:hover {
                    background-color: darkviolet;
                }

        /* Clear floats after the columns */
        .mynav_row:after {
            content: "";
            display: table;
            clear: both;
        }
    </style>
</head>
<body>
    <div class="mynav_navbar">


        <div class="mynav_dropdown">
            <button class="mynav_dropbtn">
                Category
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="mynav_dropdown-content">

                <div class="row">
                    <div class="column">

                        @Html.ActionLink("Add Category", "CreateCategory", "Category")
                    </div>

                    <div class="column">
                        @Html.ActionLink("Get list of category", "GetCategories", "Category")
                    </div>
                </div>
            </div>
        </div>
        <div class="mynav_dropdown">
            <button class="mynav_dropbtn">
                Product
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="mynav_dropdown-content">

                <div class="row">
                    <div class="column">

                        @Html.ActionLink("Add Products", "CreateProduct", "Product")
                    </div>
                    <div class="column">
                        @Html.ActionLink("Get Products", "GetProducts", "Product")
                    </div>

                </div>
            </div>
        </div>

    </div>
</body>
</html>

<div style="background-color:aqua ">
    <h3>@Html.ActionLink("Add Customer", "CreateCustomer", "Customer")</h3>
    <br />
    <h3>@Html.ActionLink("Get Customer Details", "GetCustomer", "Customer")</h3>
    <br />
    <h3>@Html.ActionLink("Add Items", "PurchaseItems", "Purchase")</h3>
    <br />
    <h3>@Html.ActionLink("Get Purchase Details", "GetPurchaseListItems", "Purchase")</h3>
    <br />
    <h3>@Html.ActionLink("Get Purchase Details By Id", "GetPurchaseById", "Purchase")</h3>
    <br />
    <h3>@Html.ActionLink("Get Reciept", "GetReciept", "Purchase")</h3>

</div>